controller_manager:
  ros__parameters:
    update_rate: 225
    
    iiwa_arm_controller:
      type: position_controllers/JointGroupPositionController
    
    iiwa_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    impedance_controller:
      type: impedance_controller/ImpedanceController
    
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    ets_state_broadcaster:
      type: external_torque_sensor_broadcaster/ExternalTorqueSensorBroadcaster

iiwa_arm_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0
    action_monitor_rate: 20.0

iiwa_arm_trajectory_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0
    action_monitor_rate: 20.0

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50

velocity_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7

effort_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7

impedance_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

gripper_controller:
  ros__parameters:
    joints:
      - joint_a8_left_finger_joint
      - joint_a8_right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    publish_rate: 20.0
    state_publish_rate: 20.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

ets_state_broadcaster:
  ros__parameters:
    sensor_name: external_torque_sensor